[package]
name = "Audiora"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
docx-rs = "0.4.18-rc19"
pdf-extract = "0.7.12"
tokio = { version = "1.42.0", features = ["full"] }
gtts = "0.1.0"
