name: Release Statically Linked Rust Binary

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    env:
      BINARY_NAME: Audiora

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            libssl-dev \
            pkg-config \
            poppler-utils \
            libasound2-dev \
            build-essential \
            cmake

      - name: Set PKG_CONFIG_PATH
        run: |
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Add Cross Compilation Targets
        run: rustup target add ${{ matrix.target }}

      - name: Build Statically Linked Binary
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cross build --target ${{ matrix.target }} --release --verbose

      - name: Strip Binary (Optional but Recommended)
        run: strip target/${{ matrix.target }}/release/$BINARY_NAME

      - name: Package Release
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/$BINARY_NAME release/
          tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.AUDI_TOKEN }}
