name: Release Statically Linked Rust Binary

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl       # Linux (musl)
          - aarch64-unknown-linux-musl      # ARM Linux (musl)

    env:
      BINARY_NAME: Audiora

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            pkg-config \
            build-essential \
            libssl-dev \
            libasound2-dev \
            cmake

      - name: Install Targets for Cross Compilation
        run: |
          rustup target add x86_64-unknown-linux-musl
          rustup target add aarch64-unknown-linux-musl

      - name: Build with Cross
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: |
          cross build --target ${{ matrix.target }} --release --verbose

      - name: Create Release Archive
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/$BINARY_NAME release/
          tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.AUDI_TOKEN }}
