name: Release Statically Linked Rust Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    env:
      BINARY_NAME: Audiora

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            libasound2-dev \
            pkg-config \
            build-essential \
            libssl-dev \
            poppler-utils \
            cmake

      - name: Build ALSA for musl
        if: contains(matrix.target, 'musl')
        run: |
          wget https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.10.tar.bz2
          tar xjf alsa-lib-1.2.10.tar.bz2
          cd alsa-lib-1.2.10
          ./configure --prefix=/usr/local/musl --host=x86_64-linux-musl --disable-python
          make
          sudo make install
          echo "/usr/local/musl/lib" | sudo tee /etc/ld.so.conf.d/musl.conf
          sudo ldconfig

      - name: Build with Cross
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_PATH: /usr/local/musl/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cross build --target ${{ matrix.target }} --release

      - name: Create Release Archive
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/$BINARY_NAME release/
          tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.AUDI_TOKEN }}