name: Release Statically Linked Rust Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    env:
      BINARY_NAME: Audiora

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            libpulse-dev \
            pkg-config \
            build-essential \
            libssl-dev \
            poppler-utils \
            cmake \
            libasound2-dev

      - name: Configure Rodio for PulseAudio
        run: |
          echo "[target.${{ matrix.target }}.dependencies.rodio]" >> Cargo.toml
          echo "features = [\"pulseaudio\"]" >> Cargo.toml
          echo "default-features = false" >> Cargo.toml

      - name: Set Environment Variables
        run: |
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV

      - name: Build with Cross
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
        run: cross build --target ${{ matrix.target }} --release

      - name: Create Release Archive
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/$BINARY_NAME release/
          tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.AUDI_TOKEN }}