name: Release Statically Linked Rust Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    env:
      BINARY_NAME: Audiora
      RUSTFLAGS: "-C target-feature=+crt-static"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross

      - name: Install Basic Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            pkg-config \
            build-essential \
            libssl-dev \
            poppler-utils

      - name: Build with Cross
        run: cross build --target ${{ matrix.target }} --release

      - name: Create Release Archive
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/$BINARY_NAME release/
          tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.AUDI_TOKEN }}