name: Release Statically Linked Rust Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    env:
      BINARY_NAME: Audiora

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev pkg-config

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross

      - name: Install Target for Cross Compilation
        run: rustup target add ${{ matrix.target }}

      - name: Set PKG_CONFIG_PATH for Musl
        run: |
          mkdir -p /usr/local/musl/lib/pkgconfig
          export PKG_CONFIG_PATH=/usr/local/musl/lib/pkgconfig
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"

      - name: Build with Cross
        env:
          PKG_CONFIG_PATH: /usr/local/musl/lib/pkgconfig
        run: cross build --target ${{ matrix.target }} --release --verbose

      - name: Create Release Archive
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/$BINARY_NAME release/
          tar -czvf ${{ matrix.target }}.tar.gz -C release $BINARY_NAME

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.SSH_KEY }}
