name: Build and Run Audiora

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04  # Updated to the latest Ubuntu version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Use the latest version

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.42.0  # Ensure the correct Rust version is installed

      - name: Install Dependencies and Build
        run: |
          rustup update
          cargo build --release

      - name: Copy Sample PDF to Release Directory
        run: cp ./path_to_your_repo/sample.pdf ./target/release/sample.pdf
        # Replace ./path_to_your_repo/sample.pdf with the actual path to your sample.pdf in the repo

      - name: Run the Program with Sample PDF
        if: ${{ github.event_name == 'push' }}  # Optional: Only run on pushes
        run: |
          ./target/release/audiora ./target/release/sample.pdf

  deploy:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Production (Optional)
        run: |
          echo "Deploying application..."
          # Add actual deployment commands here, e.g., scp, rsync, or publish steps
